baseurl: "/about"
url: "https://www.emersonjohnston.org"

title: emerson johnston
author:
  name: emerson johnston
  email: evj [@] stanford.edu
description: >
  sociologist, historian, ethnographer, and writer

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Include the home directory
include:
  - home

sass:
  quiet_deps: true
  silence_deprecations: [import]
  load_paths:
    - _sass
    - assets/css

minima:
  skin: classic
  nav_pages:
    - home/0about.md 
    - home/1publications.md
    - home/2projects.md
    - home/3interests.md
  show_excerpts: false

  social_links:
    - title: GitHub – evjohnston
      icon: github
      url: "https://github.com/evjohnston"
    - title: Bluesky – idenarch
      icon: bluesky
      url: "https://bsky.app/profile/idenarch.bsky.social"
    - title: Google Scholar – evjohnston
      icon: google-scholar
      url: "https://scholar.google.com/citations?user=kd2As4kAAAAJ&hl=en"
    - title: LinkedIn – evjofficial
      icon: linkedin-in
      url: "https://www.linkedin.com/in/evjofficial"
    - title: Mastodon – idenarch
      icon: mastodon
      url: "https://mastodon.social/@idenarch"