title: emerson johnston
author:
  name: emerson johnston
  email: evj [@] stanford.edu

description: >
  sociologist, historian, ethnographer, and writer

theme: minima

baseurl: "/home"  # 👈 IMPORTANT so portfolio pages are served from /home/

plugins:
  - jekyll-feed
  - jekyll-seo-tag

sass:
  quiet_deps: true
  silence_deprecations: [import]

minima:
  # Minima skin selection. Available skins are:
  #   Available skins:
  #     * classic            Default, light color scheme.
  #     * dark               Dark variant of the classic skin.
  #     * auto               Adaptive skin based on the default classic and dark skins.
  #     * solarized-light    Light variant of solarized color scheme.
  #     * solarized-dark     Dark variant of solarized color scheme.
  #     * solarized          Adaptive skin for solarized color scheme skins.
  skin: classic

  # Specific pages for site navigation.
  #   If you wish to link only specific pages in the site-navigation, use this and list
  #   the `path` property (as represented via Liquid) of the pages in the order they
  #   should be rendered.
  nav_pages:
    - 1publications.md
    - 2projects.md
    - 3interests.md

  # Set to `true` to show excerpts on the homepage.
  show_excerpts: false

  # Minima date format.
  #   The default value is "%b %d, %Y" (e.g. Nov 14, 2023).
  #   Refer to https://shopify.github.io/liquid/filters/date/ for valid values.
  # date_format: "%b-%d-%Y"

  # Social Media Links
  #   Renders icons via Font Awesome Free webfonts CDN, based on ordered list of entries.
  #   Entry keys:
  #     * title    Tooltip rendered on hovering over icon.
  #     * icon     Font Awesome icon id. `github` corresponds to `fa-github`.
  #     * url      Full URL of social profile.
  social_links:
  - title: GitHub – evjohnston
    icon: github
    url: "https://github.com/evjohnston"
  - title: Bluesky – idenarch
    icon: bluesky
    url: "https://bsky.app/profile/idenarch.bsky.social"
  - title: Google Scholar – evjohnston
    icon: google-scholar
    url: "https://scholar.google.com/citations?user=kd2As4kAAAAJ&hl=en"
  - title: LinkedIn – evjofficial
    icon: linkedin-in
    url: "https://www.linkedin.com/in/evjofficial"
  - title: Mastodon – idenarch
    icon: mastodon
    url: "https://mastodon.social/@idenarch"